config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resource :feedback, only: %i[new create]

  resources :badges_users, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :badges_users, dependent: :delete_all
  has_many :users, through: :badges_users

  validates :name, :url, presence: true
  validates :rule_name, presence: true, uniqueness: { scope: :rule_value }
  validates_inclusion_of :rule_name, in: %w[first_try category level loser]
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_badge, only: %i[show edit update destroy]

  def show; end

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: 'Badge was successfully created'
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: 'Badge was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @badge.delete
    redirect_to admin_badges_path, notice: 'Badge was successfully deleted'
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :url, :rule_name, :rule_value)
  end
end

app/views/admin/badges/_badge.slim
tr
  td.align-middle
    = content_tag :span, badge.name, class: 'test-title'
  td.align-middle== image_tag(badge.url, class: 'badge-size')
  td.align-middle= badge.rule_name
  td.align-middle= badge.rule_value
  td.align-middle= link_to t('links.edit'), edit_admin_badge_path(badge)
  td.align-middle= link_to t('links.delete'), admin_badge_path(badge),
          data: {:confirm => t('links.message')}, method: :delete

app/views/admin/badges/_form.slim
= form_for [:admin, @badge] do |f|

  .form-group
    = f.label :name, class: 'col-form-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :url, class: 'col-form-label'
    .col-sm-10
      = f.select :url, ApplicationHelper::BADGES_URLS, {}, { class: 'form-control' }
  .form-group
    = f.label :rule_value, class: 'col-form-label'
    .col-sm-10
      = f.text_field :rule_value, class: 'form-control'
  .form-group
    = f.label :rule_name, class: 'col-form-label'
    .col-sm-10
      = f.select :rule_name, t("badge.rule_name.").invert, {}, { class: 'form-control' }

  p
    = f.submit

app/views/admin/badges/edit.slim
.container
  h1 == "Редактировать #{@badge.name}"
  .row.justify-content-start
    = render 'shared/errors', resource: @test
    = render 'form'

  = link_to t('links.back'), admin_tests_path, class: 'btn btn-secondary mt-3'

app/views/admin/badges/index.slim
.container
  .row.justify-content-start
    .col-auto
      h1
        .title.text-info = t('.header')

      =render 'shared/errors', resource: @badge

      .container
        .table.table-hover
          table.tests-table
            tr
              th = t('.name')
              th = t('.url')
              th = t('.rule_name')
              th = t('.rule_value')
              th colspan="2" = t('.actions')

              = render @badges
          .mt-5
            = link_to t('.badge_create'), new_admin_badge_path, class: 'btn btn-info mr-3'
            = link_to t('links.back'), admin_tests_path, class: 'btn btn-info'

app/views/admin/badges/new.slim
.container
  h1 = t('.header')
  .row.justify-content-start

    = render 'shared/errors', resource: @badge
    = render 'form'

  = link_to t('links.back'), admin_tests_path, class: 'btn btn-secondary mt-3'