config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resource :feedback, only: %i[new create]

  resources :badges_users, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PER_CENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids) && !time_over?

    self.success = true if successful?
    save!
  end

  def completed?
    current_question.nil?
  end

  def correct_per_cent
    (correct_questions.to_f / test.questions.count * 100).round.to_i
  end

  def successful?
    correct_per_cent >= SUCCESS_PER_CENT
  end

  def current_question_index
    test.questions.order(:id).index(current_question) + 1
  end

  def timer?
    test.time.present?
  end
  
  def timer
    test.time * 60
  end
  
  def time_left
    created_at + timer - Time.current
  end
  
  def time_over?
    timer? && time_left <= 0
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort unless answer_ids.nil?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.present?
      test.questions.order(:id).where('id > ?', current_question_id).first
    else
      test.questions.first
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :find_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def gist
    result = GistService.new(@test_passage.current_question).call

    if result.success?
      create_gist(result.html_url)
      flash[:notice] = t('.success', link: view_context.link_to("#{t('.here')}", result.html_url))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_over?
      awarded_badges = Awarder.new(@test_passage).call
      current_user.badges << awarded_badges

      session[:badges] = awarded_badges&.pluck(:name, :url)

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render 'show'
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def create_gist(gist_url)
    current_user.gists.create(
      url: gist_url,
      user: current_user,
      question: @test_passage.current_question)
  end
end

app/views/test_passages/result.slim
.title.text-info.mt-5
  h1 = t('.header', title: @test_passage.test.title)

  - if session[:badges].any?
    h4 Вы получили награды:
    .badge-list
      - session[:badges].each do |badge_details|
        span
          == image_tag(badge_details[1], class: 'badge-size mr-1')
          = badge_details[0]

.container
  .card.mt-5
    .card-body
      .card-header.bg-info = "Your success rate is: #{@test_passage.correct_per_cent} %"

    .card-body
      - if @test_passage.successful?
        p.test-success
          = 'Congratulations! You successfully passed the test.'
      - else
        p.test-failure
          = 'You failed the test. Please, try again'

    .card-footer
      = link_to 'Back', tests_path

app/views/test_passages/show.slim
.title.text-info
  h1 = t('.header', title: @test_passage.test.title)

- if @test_passage.timer?
  = content_tag :div, id: 'timer', class: 'mb-2',
        data: {timer: @test_passage.timer, time_left: @test_passage.time_left} do
    .row.justify-content-md-center
      = t('.timer-remaining')
      span#counter = @test_passage.time_left

.progress
  = content_tag :div, "#{@test_passage.correct_per_cent} %", class: 'progress-bar progress-bar-danger', \
    role: 'progressbar', data: { width: @test_passage.correct_per_cent }

.container
  .card
    .card-body
      .card-header.bg-info
        = "Question No. #{@test_passage.current_question_index} out of #{@test_passage.test.questions.count} questions."

      .card-body
        b= @test_passage.current_question.body

        = form_with url: test_passage_path(@test_passage), local: true, method: :put do |f|
          = f.collection_check_boxes :answer_ids, @test_passage.current_question.answers,
                  :id, :body, include_hidden: false do |b|
            .mt-3
              p
                = b.check_box id: "answer_ids_#{b.object.id}"
                = b.label

          p= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post

          p= f.submit t('.next')