config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resource :feedback, only: %i[new create]

  resources :badges_users, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end
end

app/views/shared/_errors.slim
- if resource.present? && resource.errors.any?
  - resource_id = resource.methods.include?(:id) ? resource.id : 0
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource_id }
    h2 = t('.header', count: resource.errors.count)

    div.ul
      - resource.errors.full_messages.each do |message|
        li = message

app/views/shared/_flash.slim
.container
  - flash.each do |type, message|
    div class=("alert #{bootstrap_class_for_flash(type)} alert-dismissible")
      a.close aria-label="close" data-dismiss="alert" href="#"  &times;
      == message

app/views/shared/_footer.en.slim
nav
  .navbar.fixed-bottom.navbar-light.bg-light
    = link_to 'Write to Us', new_feedback_path,
            class: 'btn btn-outline-secondary mr-3'
    = link_to 'Достижения', badges_users_path,
            class: 'btn btn-outline-secondary'
    .container.text-center
      p
        small #{current_year}, Ekaterina Egorova - #{link_to 'Testguru app', github_url('nuringa', 'testguru')}
      p
        small Make and pass tests with questions - #{link_to 'A project in Thinknetica online-school', 'https://www.thinknetica.com/'}

app/views/shared/_footer.ru.slim
.container
  .row.justify-content-center
    .mt-5
      = link_to 'Напишите нам', new_feedback_path,
            class: 'btn btn-outline-secondary mr-3'
      = link_to 'Достижения', badges_users_path,
              class: 'btn btn-outline-secondary'
nav
  .navbar.fixed-bottom.navbar-light.bg-light
    .container.text-center
      p
        small #{current_year} Егорова Екатерина - #{link_to 'Приложение ТестГуру', github_url('nuringa', 'testguru')}
      p
        small Отвечай на вопросы и проходи тесты - #{link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://www.thinknetica.com/'}

app/views/shared/_nav.slim
nav.navbar-expand-md.navbar-light.bg-light.mb-2

  ul.navbar-nav
    .navbar-brand.mr-auto
      = link_to 'TestGuru', root_path, class: 'btn btn-outline-info ml-2'
    - if current_user&.admin?
      li.nav-item.mr-auto
        = link_to t('.admin_panel_link'), admin_tests_path, class: 'nav-link'

    - if signed_in?
      li.nav-item
        .navbar-text
          = t('.welcome')
          b[class="user-email"] = current_user.email
      li.nav-item
        = link_to t('.log_out'), destroy_user_session_path, class: 'nav-link ml-2', method: :delete
    - else
      li.nav-item
        = link_to t('.sign_up'), new_user_registration_path, class: 'nav-link'
      li.nav-item
        = link_to t('.log_in'), new_user_session_path, class: 'nav-link'