config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resource :feedback, only: %i[new create]

  resources :badges_users, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to [:admin, @question], notice: 'Question was successfully created'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question], notice: 'Question was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    redirect_to [:admin, @question.test], alert: 'Question was destroyed' if @question.destroy
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question not found.'
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question, test = nil)
    if question.new_record?
      "Create Test \"#{test.title.capitalize}\" Question"
    else
      "Edit Test \"#{question.test.title.capitalize}\" Question"
    end

  end
end

app/views/admin/questions/_form.slim
= form_for [:admin, @test, @question] do |f|
  p= f.text_area :body
  = f.submit

app/views/admin/questions/_question.slim
tr
  td= question.id
  td= question.body
  td= link_to t('links.view'), admin_question_path(question)
  td= link_to t('links.edit'), edit_admin_question_path(question)
  td= link_to t('links.delete'), admin_question_path(question), data: {:confirm => t('links.message')}, method: :delete

app/views/admin/questions/edit.slim
.container
  .row.justify-content-start
    .col-auto
      h1= question_header(@question)

      = render 'shared/errors', resource: @question

      = render 'form'

      = link_to link_to t('links.back'), admin_test_path(@question.test)

app/views/admin/questions/new.slim
.container
  .row.justify-content-start
    .col-auto
      h1= question_header(@question, @test)

      = render 'shared/errors', resource: @question
      = render 'form'

      = link_to t('links.back'), admin_test_path(@test)

app/views/admin/questions/show.slim
.container
  .row.justify-content-start
    .col-auto
      h3= "Question #{@question.id}"

      p= @question.body

      h3 = t('.header_answers')

      = link_to t('.answer_create'), new_admin_question_answer_path(@question)
      ol= render @question.answers

      = link_to t('links.back'), admin_test_path(@question.test)